/*
This thing is like a data structure to hold one customers booking, again serializable
bookingId is autogenerated

*/

package hotel;
//Used to convert an object into a byte stream 
//(for saving to file or sending over network)
import java.io.Serializable;
import java.time.LocalDate;
public class Booking implements Serializable {
    private static final long serialVersionUID = 1L;  //Unique ID for the class during serialization. Helps Java verify compatibility when loading objects.
    private String bookingId, customerName, contact;
    private int roomNumber, days;
    private LocalDate checkInDate;
    private double totalAmount;
    private boolean active;
    public Booking(String bookingId, String customerName, String contact,
                   int roomNumber, LocalDate checkInDate, int days, double totalAmount, boolean active) {
        this.bookingId = bookingId; this.customerName = customerName; this.contact = contact;
        this.roomNumber = roomNumber; this.checkInDate = checkInDate;
        this.days = days; this.totalAmount = totalAmount; this.active = active;
    }
    public String getBookingId() { return bookingId; }
    public String getCustomerName() { return customerName; }
    public String getContact() { return contact; }
    public int getRoomNumber() { return roomNumber; }
    public LocalDate getCheckInDate() { return checkInDate; }
    public int getDays() { return days; }
    public double getTotalAmount() { return totalAmount; }
    public boolean isActive() { return active; }
    public String getStatusDisplay() { return active ? "Checked-In" : "Checked-Out"; }
    public void setActive(boolean active) { this.active = active; }
}
